[package]
name = "asp_check"
version = "0.1.0"
edition = "2024"

[dependencies]
bgpkit-broker = "0.9.2"
bgpkit-parser = "0.11.1"
env_logger = "0.11.8"
log = "0.4.28"
regex = "1.12.2"
reqwest = "0.12.24"
